// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD.Persistence.Repositories.DBContext;

#nullable disable

namespace SD.Persistence.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD.Core.Entities.Movies.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        });
                });

            modelBuilder.Entity("SD.Core.Entities.Movies.MediumType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Code");

                    b.ToTable("MediumTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "VHS",
                            Name = "Video Home System"
                        },
                        new
                        {
                            Code = "DVD",
                            Name = "Digital Versatile Disc"
                        },
                        new
                        {
                            Code = "BR",
                            Name = "Blu-ray Disc"
                        },
                        new
                        {
                            Code = "BR3D",
                            Name = "3D Blu-ray Disc"
                        },
                        new
                        {
                            Code = "BR4K",
                            Name = "4K Blu-ray Disc"
                        });
                });

            modelBuilder.Entity("SD.Core.Entities.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("MediumTypeCode")
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("IX_Movies_GenreId");

                    b.HasIndex("MediumTypeCode")
                        .HasDatabaseName("IX_Movies_MediumTypeCode");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Movies_Title");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeb15090-d5a6-46b9-a1a2-59eafb99ad24"),
                            GenreId = 1,
                            MediumTypeCode = "VHS",
                            Price = 4.9m,
                            Rating = (byte)20,
                            ReleaseDate = new DateTime(1985, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rambo"
                        },
                        new
                        {
                            Id = new Guid("92436ae8-7c68-482a-9230-f289e53e1156"),
                            GenreId = 3,
                            MediumTypeCode = "BR3D",
                            Price = 14.9m,
                            Rating = (byte)30,
                            ReleaseDate = new DateTime(2016, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Trek - Beyond"
                        },
                        new
                        {
                            Id = new Guid("15614c54-4523-4ad0-87bf-8579f38f793b"),
                            GenreId = 3,
                            MediumTypeCode = "DVD",
                            Price = 9.9m,
                            Rating = (byte)20,
                            ReleaseDate = new DateTime(1987, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars - Episode IV"
                        },
                        new
                        {
                            Id = new Guid("b4aa56ae-dc15-41dd-988f-dbaa5d0f510e"),
                            GenreId = 2,
                            MediumTypeCode = "BR",
                            Price = 12.9m,
                            Rating = (byte)10,
                            ReleaseDate = new DateTime(2005, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Ring"
                        });
                });

            modelBuilder.Entity("SD.Core.Entities.Movies.Movie", b =>
                {
                    b.HasOne("SD.Core.Entities.Movies.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SD.Core.Entities.Movies.MediumType", "MediumType")
                        .WithMany("Movies")
                        .HasForeignKey("MediumTypeCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Genre");

                    b.Navigation("MediumType");
                });

            modelBuilder.Entity("SD.Core.Entities.Movies.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("SD.Core.Entities.Movies.MediumType", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
